Repository GoogleCloudPlatform/kubeflow-distribution, pull requests merged in 2020-06, with the labels that each got.

#40 Additional instructions and fixes for private GKE
  kubeflow/Makefile
  kubeflow/README.md
  kubeflow/deploy_private.md
  kubeflow/instance/gcp_config/enable-services.yaml
  kubeflow/instance/settings.yaml
Labels: approved, lgtm, size/XL

#41 Wait for cert-manager webhook to be created.
  kubeflow/Makefile
Labels: approved, lgtm, size/XS

#45 Add kpt setters for default profile.
  Makefile
  kubeflow/instance/gcp_config/cluster_patch.yaml
  kubeflow/instance/gcp_config/nodepool_patch.yaml
  kubeflow/instance/kustomize/kubeflow-apps/default-install-config.yaml
  kubeflow/instance/kustomize/kubeflow-apps/profiles-config.yaml
  kubeflow/instance/settings.yaml
Labels: approved, lgtm, size/S

#44 Minor tweaks to the Makefile for the blueprint
  kubeflow/Makefile
Labels: approved, lgtm, size/XS

#49 Add minio gcp install config to instance
  kubeflow/instance/kustomize/kubeflow-apps/kustomization.yaml
  kubeflow/instance/kustomize/kubeflow-apps/pipeline-minio-install-config.yaml
Labels: approved, lgtm, size/XS

#50 Add CI to verify hydration works.
  .gitignore
  go.mod
  go.sum
  kubeflow/Makefile
  kubeflow/instance/kustomize/kubeflow-apps/kustomization.yaml
  prow_config.yaml
  tests/README.md
  tests/pipeline-runs/go-tests-run.yaml
  tests/validate_test.go
Labels: approved, lgtm, size/L

#57 Use gcp stack for blueprint
  kubeflow/instance/kustomize/kubeflow-apps/kustomization.yaml
  kubeflow/instance/kustomize/kubeflow-apps/pipeline-mysql-install-config.yaml
Labels: approved, lgtm, size/XS

#58 fix: add pipeline mysql install config override
  kubeflow/instance/kustomize/kubeflow-apps/kustomization.yaml
Labels: approved, lgtm, size/XS

#62 Set user email to default profile
  kubeflow/Makefile
Labels: approved, lgtm, size/M

#63 Run the mnist notebook in the periodic tests.
  prow_config.yaml
  tests/pipeline-runs/mnist-nb-pipeline-run.yaml
Labels: approved, lgtm, size/M

#64 fix(gcp): default workload identity bindings
  kubeflow/Makefile
Labels: approved, lgtm, size/XS

#66 Fix the mnist test;
  tests/pipeline-runs/mnist-nb-pipeline-run.yaml
Labels: approved, lgtm, size/S

#68 Auto deployments are now zonal not regional so update the tests.
  tests/pipeline-runs/gcp-kf-ready.yaml
  tests/pipeline-runs/mnist-nb-pipeline-run.yaml
Labels: approved, lgtm, size/XS
