Repository GoogleCloudPlatform/kubeflow-distribution, pull requests merged in 2020-09, with the labels that each got.

#120 Update management makefile
  management/Makefile
  management/instance/Kptfile
  management/instance/cluster/kustomization.yaml
  management/instance/cnrm-install-iam/kustomization.yaml
  management/instance/cnrm-install-services/kustomization.yaml
  management/instance/managed-project/iam.yaml
  management/instance/settings.yaml
Labels: approved, lgtm, ok-to-test, size/M

#133 Remove deprecated --project flag from anthoscli
  management/Makefile
Labels: approved, lgtm, needs-ok-to-test, size/XS

#135 Update kubeflow makefile
  kubeflow/Makefile
  kubeflow/instance/settings.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S

#134 Update config context
  kubeflow/hack/create_context.sh
  management/hack/create_context.sh
Labels: approved, lgtm, needs-ok-to-test, size/M
