Repository GoogleCloudPlatform/kubeflow-distribution, pull requests merged in 2020-07, with the labels that each got.

#76 Pin the manifests to a specific 1.1 tag on the 1.1 branch.
  kubeflow/Makefile
  tests/pipeline-runs/gcp-kf-ready.yaml
  tests/pipeline-runs/mnist-nb-pipeline-run.yaml
Labels: approved, lgtm, size/XS

#79 Enable xgboost test.
  prow_config.yaml
  tests/pipeline-runs/xgboost-nb-pipeline-run.yaml
Labels: approved, lgtm, size/M

#81 Automated cherry pick of #79: Enable xgboost test. Cherry pick of #79 on v1.1-branch. #79: Enable xgboost test.
  prow_config.yaml
  tests/pipeline-runs/xgboost-nb-pipeline-run.yaml
Labels: approved, lgtm, size/M

#80 feat: enable istio sidecar for kubeflow namespace
  kubeflow/instance/kustomize/namespaces/kustomization.yaml
  kubeflow/instance/kustomize/namespaces/namespaces.yaml
Labels: approved, lgtm, size/S

#84 Install knative-serving into its own namespace.
  kubeflow/Makefile
  kubeflow/instance/kustomize/knative/kustomization.yaml
Labels: approved, lgtm, size/S

#85 Cherry pick of "feat: enable istio sidecar for kubeflow namespace #80"
  kubeflow/instance/kustomize/namespaces/kustomization.yaml
  kubeflow/instance/kustomize/namespaces/namespaces.yaml
Labels: approved, lgtm, size/S

#87 Need to create the knative-serving namespace in the proper order
  kubeflow/Makefile
Labels: approved, lgtm, size/XS

#95 Convert setters from v1 to v2
  kubeflow/Makefile
  kubeflow/hack/create_kptfile.py
  kubeflow/instance/Kptfile
  kubeflow/instance/gcp_config/cluster_patch.yaml
  kubeflow/instance/gcp_config/enable-services.yaml
  kubeflow/instance/gcp_config/iam_policy.yaml
  kubeflow/instance/gcp_config/kustomization.yaml
  kubeflow/instance/gcp_config/nodepool_patch.yaml
  kubeflow/instance/kustomize/application/kustomization.yaml
  kubeflow/instance/kustomize/cert-manager-crds/kustomization.yaml
  kubeflow/instance/kustomize/cert-manager-kube-system-resources/kustomization.yaml
  kubeflow/instance/kustomize/cert-manager/kustomization.yaml
  kubeflow/instance/kustomize/cloud-endpoints/kustomization.yaml
  kubeflow/instance/kustomize/cloud-endpoints/service-accounts.yaml
  kubeflow/instance/kustomize/iap-ingress/iap-ingress-config.yaml
  kubeflow/instance/kustomize/iap-ingress/kustomization.yaml
  kubeflow/instance/kustomize/iap-ingress/service-accounts.yaml
  kubeflow/instance/kustomize/knative/kustomization.yaml
  kubeflow/instance/kustomize/kubeflow-apps/default-install-config.yaml
  kubeflow/instance/kustomize/kubeflow-apps/kustomization.yaml
  kubeflow/instance/kustomize/kubeflow-apps/pipeline-minio-install-config.yaml
  kubeflow/instance/kustomize/kubeflow-apps/pipeline-mysql-install-config.yaml
  kubeflow/instance/kustomize/kubeflow-apps/profiles-config.yaml
  kubeflow/instance/kustomize/kubeflow-apps/service-accounts.yaml
  kubeflow/instance/kustomize/kubeflow-issuer/kustomization.yaml
  kubeflow/instance/kustomize/kubeflow-istio/kustomization.yaml
  kubeflow/instance/kustomize/metacontroller/kustomization.yaml
  kubeflow/instance/kustomize/namespaces/kustomization.yaml
  kubeflow/instance/settings.yaml
  prow_config.yaml
  tests/pipeline-runs/deploy-blueprint-pipeline-run.yaml
  tests/validate_test.go
Labels: approved, lgtm, size/XL

#96 fix: ASM sidecar repeated auth error message to stackdriver
  kubeflow/Makefile
Labels: approved, lgtm, size/S

#88 Automated cherry pick of #84: Install knative-serving into its own namespace. #87: Need to create the knative-serving namespace in the proper Cherry pick of #84 #87 on v1.1-branch. #84: Install knative-serving into its own namespace. #87: Need to create the knative-serving namespace in the proper
  kubeflow/Makefile
  kubeflow/instance/kustomize/knative/kustomization.yaml
Labels: approved, lgtm, size/S

#97 Automated cherry pick of #95: Convert setters from v1 to v2 Cherry pick of #95 on v1.1-branch. #95: Convert setters from v1 to v2
  kubeflow/Makefile
  kubeflow/hack/create_kptfile.py
  kubeflow/instance/Kptfile
  kubeflow/instance/gcp_config/cluster_patch.yaml
  kubeflow/instance/gcp_config/enable-services.yaml
  kubeflow/instance/gcp_config/iam_policy.yaml
  kubeflow/instance/gcp_config/kustomization.yaml
  kubeflow/instance/gcp_config/nodepool_patch.yaml
  kubeflow/instance/kustomize/application/kustomization.yaml
  kubeflow/instance/kustomize/cert-manager-crds/kustomization.yaml
  kubeflow/instance/kustomize/cert-manager-kube-system-resources/kustomization.yaml
  kubeflow/instance/kustomize/cert-manager/kustomization.yaml
  kubeflow/instance/kustomize/cloud-endpoints/kustomization.yaml
  kubeflow/instance/kustomize/cloud-endpoints/service-accounts.yaml
  kubeflow/instance/kustomize/iap-ingress/iap-ingress-config.yaml
  kubeflow/instance/kustomize/iap-ingress/kustomization.yaml
  kubeflow/instance/kustomize/iap-ingress/service-accounts.yaml
  kubeflow/instance/kustomize/knative/kustomization.yaml
  kubeflow/instance/kustomize/kubeflow-apps/default-install-config.yaml
  kubeflow/instance/kustomize/kubeflow-apps/kustomization.yaml
  kubeflow/instance/kustomize/kubeflow-apps/pipeline-minio-install-config.yaml
  kubeflow/instance/kustomize/kubeflow-apps/pipeline-mysql-install-config.yaml
  kubeflow/instance/kustomize/kubeflow-apps/profiles-config.yaml
  kubeflow/instance/kustomize/kubeflow-apps/service-accounts.yaml
  kubeflow/instance/kustomize/kubeflow-issuer/kustomization.yaml
  kubeflow/instance/kustomize/kubeflow-istio/kustomization.yaml
  kubeflow/instance/kustomize/metacontroller/kustomization.yaml
  kubeflow/instance/kustomize/namespaces/kustomization.yaml
  kubeflow/instance/settings.yaml
  prow_config.yaml
  tests/pipeline-runs/deploy-blueprint-pipeline-run.yaml
  tests/validate_test.go
Labels: approved, lgtm, size/XL

#98 Update to the the rc1 candidate of manifests.
  kubeflow/Makefile
Labels: approved, lgtm, size/XS

#99 Cherry pick of "fix: ASM sidecar repeated auth error message to stackdriver #96"
  kubeflow/Makefile
Labels: approved, lgtm, size/S

#100 Bump v1.1 to rc.2
  kubeflow/Makefile
Labels: approved, lgtm, size/XS

#101 Bump manifests to v1.1.0
  kubeflow/Makefile
Labels: approved, lgtm, size/XS
