Repository GoogleCloudPlatform/kubeflow-distribution, pull requests merged in 2020-11, with the labels that each got.

#137 Improve kf set values
  kubeflow/Makefile
  kubeflow/instance/Kptfile
  management/Makefile
Labels: approved, lgtm, ok-to-test, size/M

#147 Add back the ZONE variable in kf makefile
  kubeflow/Makefile
Labels: approved, lgtm, needs-ok-to-test, size/XS

#151 Fix broken link to kpt blueprints page
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#152 feat(management): upgrade to config connector operator install
  management/Makefile
  management/README.md
  packages/hack/example-config.sh
  packages/hack/reset.sh
  packages/management/Kptfile
  packages/management/cluster/README.md
  packages/management/cluster/cluster.yaml
  packages/management/cluster/enable-services.yaml
  packages/management/cluster/kustomization.yaml
  packages/management/cluster/nodepool.yaml
  packages/management/cnrm-install/README.md
  packages/management/cnrm-install/iam/iam.yaml
  packages/management/cnrm-install/iam/kustomization.yaml
  packages/management/cnrm-install/install-system/configconnector-instance.yaml
  packages/management/cnrm-install/install-system/configconnector-operator.yaml
  packages/management/cnrm-install/install-system/kustomization.yaml
  packages/management/cnrm-install/services/enable-services.yaml
  packages/management/cnrm-install/services/kustomization.yaml
  tests/management/.gitignore
  tests/management/Makefile
  tests/management/README.md
  tests/management/storagebucket.yaml
Labels: approved, lgtm, size/XL

#153 Merge validate-values and validate-name-length
  management/Makefile
Labels: approved, lgtm, size/XS

#156 Fix kubeflow makefile test
  tests/validate_test.go
Labels: approved, lgtm, size/XS

#155 feat: install and upgrade instructions for management cluster in Kubeflow 1.2
  management/Makefile
  management/README.md
  packages/management/cluster/cluster.yaml
  packages/management/cluster/enable-services.yaml
  packages/management/cluster/nodepool.yaml
  packages/management/cnrm-install/README.md
  tests/management/.gitignore
  tests/management/Makefile
  tests/management/README.md
  tests/management/example.env
  tests/management/resources/Kptfile
  tests/management/resources/storagebucket.yaml
  tests/management/storagebucket.yaml
Labels: approved, lgtm, size/L

#163 feat: refactor management/Makefile to make upgrade easier. Part of #90 and #158
  kubeflow/README.md
  management/Makefile
  management/README.md
  management/set-values.sh
  packages/management/Makefile
  packages/management/hack/create_context.sh
  tests/management/Makefile
  tests/management/example.env
Labels: approved, lgtm, size/L

#162 feat: kick backend-updater after apply
  kubeflow/Makefile
Labels: approved, lgtm, size/XS

#161 Revert "Explicitly disable container native load balancing (neg) "
  kubeflow/instance/kustomize/iap-ingress/kustomization.yaml
  kubeflow/instance/kustomize/iap-ingress/service.yaml
Labels: approved, lgtm, size/XS

#166 feat(management): update instructions to use kpt cfg set -R to set both packages. Part of #158
  management/Makefile
  management/README.md
  management/set-values.sh
  packages/management/Makefile
  packages/management/cnrm-install/README.md
Labels: approved, lgtm, size/L

#168 chore(release): pin kubeflow/manifests v1.2-branch
  kubeflow/Makefile
Labels: approved, size/XS

#169 feat: revert to kf 1.1 installation UX for kubeflow package
  kubeflow/Makefile
  kubeflow/instance/Kptfile
  tests/validate_test.go
Labels: approved, lgtm, size/L

#170 feat: validate cluster name by regex. Fixes #154
  kubeflow/Makefile
  packages/management/Makefile
Labels: approved, lgtm, size/M

#171 feat: wait for all GCP resources and more helpful error message
  kubeflow/Makefile
Labels: approved, lgtm, size/S

#172 test: rename vars to GH_ to avoid conflict with system env
  tests/management/Makefile
  tests/management/example.env
Labels: approved, lgtm, size/S

#173 fix: kustomize 3.8 compatibility
  kubeflow/Makefile
  packages/management/Makefile
Labels: approved, lgtm, size/XS
