Repository GoogleCloudPlatform/kubeflow-distribution, pull requests merged in 2020-05, with the labels that each got.

#7 Fix various bugs as part of setting up auto deployments
  kubeflow/Makefile
  kubeflow/README.md
  kubeflow/hack/check_domain_length.sh
  kubeflow/instance/gcp_config/kustomization.yaml
  kubeflow/upstream/README.md
  management/instance/cnrm-install-per-namespace/per-namespace-components.yaml
Labels: approved, lgtm, size/M

#11 We need to add a CNRM config to enable ASM services.
  kubeflow/Makefile
  kubeflow/README.md
  kubeflow/hack/create_context.sh
  kubeflow/instance/gcp_config/enable-services.yaml
  kubeflow/instance/gcp_config/kustomization.yaml
  management/hack/create_context.sh
Labels: approved, lgtm, size/L

#17 Fix env var in README.md
  management/README.md
Labels: approved, lgtm, size/XS

#18 Fix kcc install instruction
  management/README.md
Labels: approved, lgtm, size/XS

#20 Fix upstream folder's location not set
  kubeflow/README.md
Labels: approved, lgtm, size/XS

#21 Fix apply got secret already exists the 2nd time
  kubeflow/Makefile
Labels: approved, lgtm, size/XS

#28 First pass at instructions using ACM
  kubeflow/Makefile
  kubeflow/README.md
Labels: approved, lgtm, size/L

#19 Fix cnrm instance commands
  management/README.md
Labels: approved, lgtm, size/XS
