Repository GoogleCloudPlatform/kubeflow-distribution, pull requests merged in 2021-04, with the labels that each got.

#207 docs: update release doc
  docs/dev/release.md
Labels: approved, lgtm, size/S

#218 (org) Add zijianjoy to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#223 (cleanup) Remove application from deployment steps. Fix #221
  kubeflow/Makefile
  kubeflow/common/cloud-endpoints/kustomization.yaml
  kubeflow/common/iap-ingress/v3/kustomization.yaml
Labels: approved, lgtm, size/XS

#220 (cnrm) Update cnrm operator version. Fix #219
  packages/management/cnrm-install/install-system/configconnector-operator.yaml
Labels: approved, lgtm, size/S

#215 (cluster) Use STABLE release channel, change machineType to e2-standard-8. Fix #213, Fix #214
  kubeflow/Makefile
  kubeflow/common/cluster/upstream/cluster.yaml
  packages/gcp-resources/cnrm/cluster/cluster.yaml
Labels: approved, lgtm, size/M

#212 (knative, kfserving, cert-manager) Build working solution for kfserving integration
  kubeflow/Makefile
  kubeflow/common/cert-manager/cert-manager-1-3/cert-manager/base/kustomization.yaml
  kubeflow/common/cert-manager/cert-manager-1-3/cert-manager/kubeflow-issuer/cluster-issuer.yaml
  kubeflow/common/cert-manager/cert-manager-1-3/cert-manager/kubeflow-issuer/kustomization.yaml
  kubeflow/common/cert-manager/cert-manager-1-3/cert-manager/overlays/letsencrypt/cluster-issuer.yaml
  kubeflow/common/cert-manager/cert-manager-1-3/cert-manager/overlays/letsencrypt/kustomization.yaml
  kubeflow/common/cert-manager/cert-manager-1-3/cert-manager/overlays/letsencrypt/params.env
  kubeflow/common/cert-manager/cert-manager-1-3/cert-manager/overlays/letsencrypt/params.yaml
  kubeflow/common/cert-manager/cert-manager-1-3/cert-manager/overlays/self-signed/kustomization.yaml
  kubeflow/common/cert-manager/kustomization.yaml
  kubeflow/common/knative/knative-0-22-0/net-istio.yaml
  kubeflow/common/knative/knative-0-22-0/serving-core.yaml
  kubeflow/common/knative/knative-0-22-0/serving-crds.yaml
  kubeflow/common/knative/kustomization.yaml
  kubeflow/common/knative/patches/namespace-patch.yaml
  kubeflow/pull-upstream.sh
Labels: approved, lgtm, size/XXL

#225 (asm) Use kpt to set asm namepsace label, use revision to download install_asm script and package. Issue #144, Fix #224
  kubeflow/apps/profiles/Kptfile
  kubeflow/apps/profiles/namespace-labels.yaml
  kubeflow/common/asm/Makefile
  kubeflow/common/knative/Kptfile
  kubeflow/common/knative/patches/namespace-patch.yaml
  kubeflow/common/kubeflow-namespace/Kptfile
  kubeflow/common/kubeflow-namespace/namespace-patch.yaml
  kubeflow/env.sh
  kubeflow/kpt-set.sh
Labels: approved, lgtm, size/L

#226 (asm) Patch istio-ingressgateway annotations for IAP. Fix #216
  kubeflow/common/asm/Makefile
  kubeflow/common/asm/options/ingressgateway-iap.yaml
Labels: approved, lgtm, size/M

#234 (Makefile) Run make apply-v3 to apply all components and deployment steps. #230
  kubeflow/Makefile
  kubeflow/apps/kfserving/Makefile
  kubeflow/common/asm/Makefile
  kubeflow/common/cert-manager/Makefile
  kubeflow/common/cloud-endpoints/kustomization.yaml
  kubeflow/common/cnrm/Makefile
  kubeflow/common/iap-secret/Makefile
  kubeflow/common/knative/Makefile
  kubeflow/common/kubeflow-issuer/kustomization.yaml
  kubeflow/pull-upstream.sh
Labels: approved, lgtm, size/L

#235 (Makefile) Address comments from PR#234
  kubeflow/Makefile
  kubeflow/apps/kfserving/Makefile
  kubeflow/common/asm/Makefile
  kubeflow/common/cert-manager/Makefile
  kubeflow/common/cnrm/Makefile
  kubeflow/common/iap-ingress/Makefile
  kubeflow/common/iap-secret/Makefile
  kubeflow/common/iap-secret/check_oauth_secret.sh
  kubeflow/common/knative/Makefile
  kubeflow/hack/apply_component.sh
Labels: approved, lgtm, size/L

#238 (Makefile) Integrate iap-secret, kubeflow-issuer to their own parent packages
  kubeflow/Makefile
  kubeflow/common/cert-manager/Makefile
  kubeflow/common/iap-ingress/Makefile
  kubeflow/common/iap-ingress/check_oauth_secret.sh
  kubeflow/common/iap-secret/Makefile
  kubeflow/common/kubeflow-issuer/kustomization.yaml
Labels: approved, size/M

#236 (kubeflow/manifests) Upgrade upstream to Kubeflow 1.3. Fix #233
  kubeflow/apps/katib/kustomization.yaml
  kubeflow/pull-upstream.sh
Labels: approved, lgtm, size/XS

#240 chore: fix pull-upstream.sh, Fixes #239
  kubeflow/common/istio/kustomization.yaml
  kubeflow/pull-upstream.sh
Labels: approved, lgtm, size/S

#241 (README) Update deployment instruction for Kubeflow and Management clusters
  README.md
  kubeflow/README.md
  management/README.md
Labels: approved, lgtm, size/L

#244 (Cluster) Set starting k8s version to be 1.18. Fix #243
  kubeflow/common/cluster/upstream/cluster.yaml
Labels: approved, lgtm, size/XS

#246 Update README.md
  README.md
Labels: approved, size/XS

#247 (Makefile) Finish complete lifecycle of kubeflow management, clean up old commands. Fix #230
  kubeflow/Makefile
  kubeflow/README.md
  kubeflow/apps/kfserving/Makefile
  kubeflow/apps/kubeflow-apps/Kptfile
  kubeflow/apps/profiles/Kptfile
  kubeflow/common/asm/Makefile
  kubeflow/common/cert-manager/Makefile
  kubeflow/common/cnrm/Makefile
  kubeflow/common/iap-ingress/Makefile
  kubeflow/common/istio/kustomization.yaml
  kubeflow/common/knative/Makefile
  kubeflow/hack/apply_component.sh
  kubeflow/hack/clean_build.sh
  kubeflow/pull-upstream.sh
Labels: approved, lgtm, size/L

#242 chore: clean up common/iap-ingress, rm unused packages
  kubeflow/common/iap-ingress/Makefile
  kubeflow/common/iap-ingress/base/cert.yaml
  kubeflow/common/iap-ingress/base/iap-ingress-config.yaml
  kubeflow/common/iap-ingress/base/kustomization.yaml
  kubeflow/common/iap-ingress/base/params.env
  kubeflow/common/iap-ingress/kustomization.yaml
  kubeflow/common/iap-ingress/overlays/application/application.yaml
  kubeflow/common/iap-ingress/overlays/application/kustomization.yaml
  kubeflow/common/iap-ingress/overlays/certmanager/certificate.yaml
  kubeflow/common/iap-ingress/overlays/certmanager/job.yaml
  kubeflow/common/iap-ingress/overlays/certmanager/kustomization.yaml
  kubeflow/common/iap-ingress/overlays/gcp-credentials/deployment.yaml
  kubeflow/common/iap-ingress/overlays/gcp-credentials/kustomization.yaml
  kubeflow/common/iap-ingress/overlays/gcp-credentials/stateful-set.yaml
  kubeflow/common/iap-ingress/overlays/managed-cert/cert.yaml
  kubeflow/common/iap-ingress/overlays/managed-cert/kustomization.yaml
  kubeflow/common/iap-ingress/service-accounts.yaml
  kubeflow/common/iap-ingress/v3/kustomization.yaml
  packages/cloud-endpoints/base/cluster-role-binding.yaml
  packages/cloud-endpoints/base/cluster-role.yaml
  packages/cloud-endpoints/base/composite-controller.yaml
  packages/cloud-endpoints/base/crd.yaml
  packages/cloud-endpoints/base/deployment.yaml
  packages/cloud-endpoints/base/gcp-credentials-patch.yaml
  packages/cloud-endpoints/base/kustomization.yaml
  packages/cloud-endpoints/base/params.env
  packages/cloud-endpoints/base/params.yaml
  packages/cloud-endpoints/base/service-account.yaml
  packages/cloud-endpoints/base/service.yaml
  packages/cloud-endpoints/overlays/application/application.yaml
  packages/cloud-endpoints/overlays/application/kustomization.yaml
  packages/cloud-endpoints/overlays/gcp-credentials/gcp-credentials-patch.yaml
  packages/cloud-endpoints/overlays/gcp-credentials/kustomization.yaml
  packages/iap-gateway/base/istio-ingressgateway.yaml
  packages/iap-gateway/base/kustomization.yaml
  packages/iap-ingress/base/backend-config.yaml
  packages/iap-ingress/base/cloud-endpoint.yaml
  packages/iap-ingress/base/cluster-role-binding.yaml
  packages/iap-ingress/base/cluster-role.yaml
  packages/iap-ingress/base/config-map.yaml
  packages/iap-ingress/base/deployment.yaml
  packages/iap-ingress/base/ingress.yaml
  packages/iap-ingress/base/kustomization.yaml
  packages/iap-ingress/base/params.env
  packages/iap-ingress/base/params.yaml
  packages/iap-ingress/base/policy.yaml
  packages/iap-ingress/base/service-account.yaml
  packages/iap-ingress/base/service.yaml
  packages/iap-ingress/base/stateful-set.yaml
  packages/iap-ingress/overlays/application/application.yaml
  packages/iap-ingress/overlays/application/kustomization.yaml
  packages/iap-ingress/overlays/certmanager/certificate.yaml
  packages/iap-ingress/overlays/certmanager/job.yaml
  packages/iap-ingress/overlays/certmanager/kustomization.yaml
  packages/iap-ingress/overlays/gcp-credentials/deployment.yaml
  packages/iap-ingress/overlays/gcp-credentials/kustomization.yaml
  packages/iap-ingress/overlays/gcp-credentials/stateful-set.yaml
  packages/iap-ingress/overlays/managed-cert/kustomization.yaml
  packages/iap-ingress/v3/kustomization.yaml
Labels: approved, size/XXL

#248 (Makefile) clean up kustomization and Makefile
  kubeflow/Makefile
  kubeflow/README.md
  kubeflow/apps/kubeflow-apps/Kptfile
  kubeflow/apps/kubeflow-apps/apps/Kptfile
  kubeflow/apps/kubeflow-apps/apps/OWNERS
  kubeflow/apps/kubeflow-apps/apps/README.md
  kubeflow/apps/kubeflow-apps/apps/config/params.env
  kubeflow/apps/kubeflow-apps/apps/kustomization.yaml
  kubeflow/apps/kubeflow-apps/apps/workload-identity-bindings-patch.yaml
  kubeflow/apps/kubeflow-apps/default-install-config.yaml
  kubeflow/apps/kubeflow-apps/kustomization.yaml
  kubeflow/apps/kubeflow-apps/pipeline-minio-install-config.yaml
  kubeflow/apps/kubeflow-apps/pipeline-mysql-install-config.yaml
  kubeflow/apps/kubeflow-apps/service-accounts.yaml
  kubeflow/common/cert-manager/Makefile
  kubeflow/common/cert-manager/kustomization.yaml
  kubeflow/common/config-kubeflow/kustomization.yaml
  kubeflow/common/config-kubeflow/workload-identity-bindings-patch.yaml
  kubeflow/common/istio/kustomization.yaml
  kubeflow/hack/delete_gcp.sh
Labels: approved, lgtm, size/XL
