Repository GoogleCloudPlatform/kubeflow-distribution, pull requests merged in 2021-05, with the labels that each got.

#250 Remove jlewi@ from OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#253 (management) Add managed project IAM file and kptfile. Partial #252
  management/Kptfile
  management/managed-project/README.md
  management/managed-project/iam.yaml
Labels: approved, lgtm

#255 (env.sh) Move all envrionment variable config to env.sh. Partial #254.
  kubeflow/env.sh
  kubeflow/kpt-set.sh
Labels: approved, lgtm, size/XS

#245 (iap-ingress) Patch BackendConfig healthcheck port with the correct port number
  kubeflow/common/iap-ingress/base/cluster-role.yaml
  kubeflow/common/iap-ingress/base/config-map.yaml
Labels: approved, lgtm, needs-ok-to-test, size/M

#262 (profile-controller) Adopt v1.3.0-gcp profile controller
  kubeflow/apps/profiles/kustomization.yaml
  kubeflow/apps/profiles/namespace-labels.yaml
  kubeflow/apps/profiles/patches/manager.yaml
  kubeflow/apps/profiles/patches/namespace-labels.yaml
Labels: approved, lgtm, size/M

#259 feat(kfp): use managed storage -- GCS and CloudSQL. Fixes kubeflow/pipelines#4356
  kubeflow/apps/pipeline/Kptfile
  kubeflow/apps/pipeline/Makefile
  kubeflow/apps/pipeline/cloudsql/cnrm/enable-services.sh
  kubeflow/apps/pipeline/cloudsql/cnrm/iam.yaml
  kubeflow/apps/pipeline/cloudsql/cnrm/kustomization.yaml
  kubeflow/apps/pipeline/cloudsql/cnrm/proxy-gsa.yaml
  kubeflow/apps/pipeline/cloudsql/cnrm/sql-instance.yaml
  kubeflow/apps/pipeline/cloudsql/cnrm/sql-user-root.yaml
  kubeflow/apps/pipeline/cloudsql/pipeline-install-config-patch.yaml
  kubeflow/apps/pipeline/cloudsql/proxy/kustomization.yaml
  kubeflow/apps/pipeline/cloudsql/proxy/workload-identity-binding-patch.yaml
  kubeflow/apps/pipeline/cnrm/kustomization.yaml
  kubeflow/apps/pipeline/gcs/cnrm/bucket.yaml
  kubeflow/apps/pipeline/gcs/cnrm/iam.yaml
  kubeflow/apps/pipeline/gcs/cnrm/kustomization.yaml
  kubeflow/apps/pipeline/gcs/minio-gateway/kustomization.yaml
  kubeflow/apps/pipeline/gcs/minio-gateway/workload-identity-binding-patch.yaml
  kubeflow/apps/pipeline/gcs/pipeline-install-config-patch.yaml
  kubeflow/apps/pipeline/kustomization.yaml
  kubeflow/apps/pipeline/patches/workload-identity-binding.yaml
  kubeflow/common/cnrm/kustomization.yaml
  kubeflow/common/pipelines/upstream/Kptfile
  kubeflow/common/pipelines/upstream/disk.yaml
  kubeflow/common/pipelines/upstream/kustomization.yaml
  kubeflow/kpt-set.sh
Labels: approved, lgtm, size/XXL

#263 (management) Specify namespace in wait-gcp command. Fix #252
  kubeflow/common/cnrm/Makefile
Labels: approved, lgtm, size/XS

#269 chore: Change pipeline/ to pipelines/ . Fix #268
  kubeflow/Makefile
  kubeflow/apps/pipelines/Kptfile
  kubeflow/apps/pipelines/Makefile
  kubeflow/apps/pipelines/cloudsql/cnrm/enable-services.sh
  kubeflow/apps/pipelines/cloudsql/cnrm/iam.yaml
  kubeflow/apps/pipelines/cloudsql/cnrm/kustomization.yaml
  kubeflow/apps/pipelines/cloudsql/cnrm/proxy-gsa.yaml
  kubeflow/apps/pipelines/cloudsql/cnrm/sql-instance.yaml
  kubeflow/apps/pipelines/cloudsql/cnrm/sql-user-root.yaml
  kubeflow/apps/pipelines/cloudsql/pipeline-install-config-patch.yaml
  kubeflow/apps/pipelines/cloudsql/proxy/kustomization.yaml
  kubeflow/apps/pipelines/cloudsql/proxy/workload-identity-binding-patch.yaml
  kubeflow/apps/pipelines/cnrm/kustomization.yaml
  kubeflow/apps/pipelines/gcs/cnrm/bucket.yaml
  kubeflow/apps/pipelines/gcs/cnrm/iam.yaml
  kubeflow/apps/pipelines/gcs/cnrm/kustomization.yaml
  kubeflow/apps/pipelines/gcs/minio-gateway/kustomization.yaml
  kubeflow/apps/pipelines/gcs/minio-gateway/workload-identity-binding-patch.yaml
  kubeflow/apps/pipelines/gcs/pipeline-install-config-patch.yaml
  kubeflow/apps/pipelines/kustomization.yaml
  kubeflow/apps/pipelines/patches/ml-pipeline-authorization-policy-patch.yaml
  kubeflow/apps/pipelines/patches/ml-pipeline-deployment-patch.yaml
  kubeflow/apps/pipelines/patches/workload-identity-binding.yaml
  kubeflow/kpt-set.sh
  kubeflow/pull-upstream.sh
Labels: approved, lgtm, size/S

#273 chore: clean up packages
  packages/hack/example-config.sh
  packages/hack/reset.sh
  packages/management/Makefile
  packages/management/cluster/README.md
  packages/management/cluster/enable-services.yaml
  packages/management/cluster/kustomization.yaml
  packages/management/cnrm-install/README.md
  packages/management/cnrm-install/iam/kustomization.yaml
  packages/management/cnrm-install/install-system/configconnector-operator.yaml
  packages/management/cnrm-install/install-system/kustomization.yaml
  packages/management/cnrm-install/services/enable-services.yaml
  packages/management/cnrm-install/services/kustomization.yaml
  packages/management/hack/create_context.sh
  packages/profiles/base/deployment_patch.yaml
  packages/profiles/base/kustomization.yaml
  packages/profiles/base/namespace-labels.yaml
Labels: approved, lgtm, size/XL

#237 (ASM) Add instruction about how to upgrade ASM. Partial #144
  kubeflow/common/asm/Makefile
  kubeflow/common/knative/Kptfile
  kubeflow/common/knative/patches/namespace-patch.yaml
  kubeflow/common/kubeflow-namespace/Kptfile
  kubeflow/env.sh
  kubeflow/kpt-set.sh
Labels: approved, lgtm, size/M

#276 fix(kfp): kfp ui forward GCP user id header. Fixes #261
  kubeflow/apps/pipelines/kustomization.yaml
  kubeflow/apps/pipelines/patches/ml-pipeline-ui-deployment-patch.yaml
Labels: approved, size/S

#274 feat: allow choosing components. Part of #275
  kubeflow/Makefile
  kubeflow/config.yaml
Labels: approved, lgtm, size/L

#277 (ASM) Upgrade ASM to latest available version
  kubeflow/common/asm/Makefile
  kubeflow/env.sh
Labels: approved, lgtm, size/S

#280 (chore) Address comment for PR #279
  kubeflow/apps/kfserving/Kptfile
  kubeflow/apps/kfserving/Makefile
  kubeflow/hack/delete_gcp.sh
Labels: approved, lgtm, size/XS

#281 (chore) Add changelog for future release
  CHANGELOG.md
Labels: approved, lgtm, size/S
