Repository GoogleCloudPlatform/kubeflow-distribution, pull requests merged in 2021-09, with the labels that each got.

#284 feat: make KFP v2 compatible mode work out of the box
  Makefile
  kubeflow/apps/kfserving/Kptfile
  kubeflow/apps/pipelines/Kptfile
  kubeflow/apps/pipelines/Makefile
  kubeflow/apps/pipelines/gcs/pipeline-install-config-patch.yaml
  kubeflow/apps/pipelines/kustomization.yaml
  kubeflow/apps/pipelines/pull-upstream.sh
  kubeflow/kpt-set.sh
  kubeflow/pull-upstream.sh
Labels: approved, lgtm, size/M, ok-to-test

#303 upgrade: Kubeflow 1.4.0-rc.0 upgrade structure adjustment. Partial #302
  kubeflow/apps/pipelines/pull-upstream.sh
  kubeflow/apps/profiles/kustomization.yaml
  kubeflow/apps/tf-training/kustomization.yaml
  kubeflow/apps/training-operator/kustomization.yaml
  kubeflow/config.yaml
  kubeflow/pull-upstream.sh
Labels: approved, lgtm, size/M

#307 kfserving: Apply userid-header and userid-prefix patch for KFServing web app. Fix #306
  kubeflow/apps/kfserving/deployment-patch.yaml
  kubeflow/apps/kfserving/kustomization.yaml
Labels: approved, lgtm, size/S

#305 ASM: Upgrade ASM from 1.9.3 to 1.10.4. Fix #304
  kubeflow/apps/pipelines/pull-upstream.sh
  kubeflow/common/asm/Makefile
  kubeflow/common/asm/README.md
  kubeflow/common/asm/asm/Kptfile
  kubeflow/common/asm/asm/canonical-service/controller.yaml
  kubeflow/common/asm/asm/cluster/cluster.yaml
  kubeflow/common/asm/asm/cluster/nodepool.yaml
  kubeflow/common/asm/asm/identity-provider/googleidp.yaml
  kubeflow/common/asm/asm/identity-provider/identityprovider-crd.yaml
  kubeflow/common/asm/asm/istio/expansion/README.md
  kubeflow/common/asm/asm/istio/expansion/expose-istiod.yaml
  kubeflow/common/asm/asm/istio/expansion/expose-services.yaml
  kubeflow/common/asm/asm/istio/expansion/gen-eastwest-gateway.sh
  kubeflow/common/asm/asm/istio/expansion/vm-eastwest-gateway.yaml
  kubeflow/common/asm/asm/istio/istio-operator.yaml
  kubeflow/common/asm/asm/istio/istiod-service.yaml
  kubeflow/common/asm/asm/istio/options/audit-authorizationpolicy.yaml
  kubeflow/common/asm/asm/istio/options/citadel-ca.yaml
  kubeflow/common/asm/asm/istio/options/cloud-tracing.yaml
  kubeflow/common/asm/asm/istio/options/cni-gcp.yaml
  kubeflow/common/asm/asm/istio/options/cni-onprem.yaml
  kubeflow/common/asm/asm/istio/options/egressgateways.yaml
  kubeflow/common/asm/asm/istio/options/envoy-access-log.yaml
  kubeflow/common/asm/asm/istio/options/hub-meshca.yaml
  kubeflow/common/asm/asm/istio/options/iap-operator.yaml
  kubeflow/common/asm/asm/istio/options/internal-load-balancer.yaml
  kubeflow/common/asm/asm/istio/options/managed-control-plane-webhooks.yaml
  kubeflow/common/asm/asm/istio/options/managed-control-plane.yaml
  kubeflow/common/asm/asm/istio/options/multicloud.yaml
  kubeflow/common/asm/asm/istio/options/multicluster.yaml
  kubeflow/common/asm/asm/istio/options/multiproject.yaml
  kubeflow/common/asm/asm/istio/options/private-ca.yaml
  kubeflow/common/asm/asm/istio/options/prometheus.yaml
  kubeflow/common/asm/asm/istio/options/revisioned-custom-ingressgateway.yaml
  kubeflow/common/asm/asm/istio/options/revisioned-istio-ingressgateway.yaml
  kubeflow/common/asm/asm/istio/options/v1beta1-crds.yaml
  kubeflow/common/asm/asm/istio/options/vm.yaml
  kubeflow/common/asm/asm/project/enable-services.yaml
  kubeflow/common/asm/asm/third-party/grafana.yaml
  kubeflow/common/asm/asm/third-party/kiali.yaml
  kubeflow/common/asm/asm/third-party/prometheus.yaml
  kubeflow/common/asm/install_asm
  kubeflow/common/asm/install_asm.sha256
  kubeflow/config.yaml
  kubeflow/env.sh
Labels: approved, lgtm, size/XXL

#312 management: Makefile update for management cluster (kpt). Partial #308
  management/Makefile
Labels: approved, lgtm, size/S

#316 profiles: Use upstream profiles image instead of gcp in-house one. Fix #315
  kubeflow/apps/profiles/kustomization.yaml
Labels: approved, lgtm, size/XS

#314 kustomize: Use labelTransformer to replace commonLabels. Fix #298
  kubeflow/apps/profiles/kustomization.yaml
  kubeflow/apps/profiles/label-transformer.yaml
  kubeflow/common/knative/kustomization.yaml
  kubeflow/common/knative/label-transformer.yaml
Labels: approved, lgtm, size/M

#318 Upgrade kpt 1.0.0-beta.6 and Kubeflow manifests 1.4.0-rc.1. Fix #309
  kubeflow/apps/pipelines/pull-upstream.sh
  kubeflow/pull-upstream.sh
Labels: approved, lgtm, size/M

#323 fix latest kpt change using sub-package krmignore
  kubeflow/apps/pipelines/.krmignore
Labels: approved, lgtm

#322 remove GKE image pin and use emissary executor. Fix #320
  kubeflow/apps/pipelines/kustomization.yaml
  kubeflow/common/cluster/upstream/cluster.yaml
  kubeflow/common/cluster/upstream/nodepool.yaml
Labels: approved, lgtm, size/S

#325 pull-upstream: Use the v1.4-branch upstream for now. Fix #302
  kubeflow/apps/pipelines/pull-upstream.sh
  kubeflow/pull-upstream.sh
Labels: approved, lgtm, size/XS
