Repository GoogleCloudPlatform/kubeflow-distribution, pull requests merged in 2022-07, with the labels that each got.

#364 Move `RequestAuthentication` policy creation to `iap-enabler` for gitops friendliness
  kubeflow/common/iap-ingress/base/config-map.yaml
  kubeflow/common/iap-ingress/base/kustomization.yaml
  kubeflow/common/iap-ingress/base/policy.yaml
Labels: approved, lgtm, size/S, ok-to-test

#369 Upgrade ASM to v1.13
  kubeflow/asm/Makefile
  kubeflow/asm/README.md
  kubeflow/asm/deprecated/Makefile
  kubeflow/asm/deprecated/README.md
  kubeflow/common/iap-ingress/base/config-map.yaml
  kubeflow/env.sh
  kubeflow/pull-upstream.sh
Labels: approved, lgtm, size/L

#370 Upgrade to kubeflow upstream 1.5.1, upgrade KFP upstream to 1.8.2.
  kubeflow/apps/pipelines/pull-upstream.sh
  kubeflow/pull-upstream.sh
Labels: approved, lgtm, size/XS

#374 Fix ASM/istio ingress gateway
  kubeflow/common/iap-ingress/Makefile
  kubeflow/common/iap-ingress/base/config-map.yaml
Labels: approved, lgtm, size/XS

#373 Upgrade knative to v 1.2
  kubeflow/common/.krmignore
  kubeflow/common/knative/knative-0-22-0/serving-core.yaml
  kubeflow/common/knative/knative-0-22-0/serving-crds.yaml
  kubeflow/common/knative/knative-1-2-5/net-istio.yaml
  kubeflow/common/knative/knative-1-2-5/serving-core.yaml
  kubeflow/common/knative/knative-1-2-5/serving-crds.yaml
  kubeflow/common/knative/kustomization.yaml
Labels: approved, lgtm, size/XXL
